import { ref } from 'vue';
const dictionary = {
  en: {
    zoomIn: 'Zoom in', zoomOut: 'Zoom out', mapContributors: 'contributors', seededShipment: 'Seeded sample shipment', localShipment: 'Local sample shipment', sampleWorkspace: 'Sample workspace',
    acknowledged: 'Acknowledged', notifyClient: 'Notify the assigned cargo client in this sample workspace', recordAction: 'Save corrective action', correctiveSaved: 'Corrective action recorded. The alert remains open until a normal sample reading is added.', actionHelp: 'Describe what was done and why (at least 8 characters). The action acknowledges the alert. It remains open until a new sample reading is within both configured ranges.', futureDeparture: 'A new shipment must depart in the future.', noticeAction: 'A corrective action was recorded for your shipment.',
    incident: 'Incident recorded', recordIncident: 'Record incident', incidentHelp: 'Describe the incident and context (at least 8 characters). It will be recorded in this sample shipment history.',
    app: 'Shipment workspace', dashboard: 'Overview', shipments: 'Shipments', alerts: 'Alerts', fleet: 'Fleet & drivers', history: 'History & reports', profile: 'My profile', terms: 'Terms & data', logout: 'Leave workspace', login: 'Enter sample workspace', register: 'Create local profile',
    coordinator: 'Logistics coordinator', 'cargo-client': 'Cargo client', sample: 'Local sample workspace', sampleShort: 'SAMPLE DATA', sampleNotice: 'Sample shipments and sensor readings. Changes are saved in this browser only.', sampleDate: 'Initial readings: Oct 6, 2026. No connected sensors.', persistence: 'Browser storage could not be read. Use a browser that allows local storage.',
    greeting: 'Your cold chain, in focus.', dashboardSubtitle: 'Follow each shipment. Act on the exceptions.', clientGreeting: 'Know how your cargo is travelling.', clientSubtitle: 'Temperature, route and traceability for your assigned shipments.',
    newShipment: 'Schedule shipment', totalShipments: 'Total shipments', inTransit: 'In transit', exceptions: 'Open alerts', delivered: 'Delivered', scheduled: 'Scheduled', cancelled: 'Cancelled', all: 'All', normal: 'Within range', critical: 'Out of range', offline: 'No signal', pending: 'Awaiting reading',
    activeRoutes: 'Coastal corridor', routeHelp: 'Illustrative positions from stored sample readings.', loadMap: 'Load OpenStreetMap', mapPrivacy: 'Loading the map connects to OpenStreetMap for tiles. Shipment positions are samples.', mapOffline: 'If tiles cannot load, the route and coordinates remain available below.',
    attention: 'Needs attention', noAlerts: 'No open alerts in your workspace.', openAlert: 'Review alert', viewAll: 'View all', recentShipments: 'Shipment watchlist', shipment: 'Shipment', cargo: 'Cargo', route: 'Route', thermal: 'Thermal status', temperature: 'Temperature', humidity: 'Humidity', lastReading: 'Latest sample', lifecycle: 'Trip status', customer: 'Cargo client', vehicle: 'Vehicle', driver: 'Driver', weight: 'Weight (t)', sensor: 'Sensor ID', capacity: 'Capacity (t)', plate: 'Plate', license: 'Licence reference',
    search: 'Search ID, cargo or route', filterStatus: 'Filter trip status', filterThermal: 'Filter thermal status', results: 'shipments', noResults: 'No shipments match these filters.', clearFilters: 'Clear filters', open: 'Open', back: 'Back', next: 'Continue', cancel: 'Cancel', save: 'Save changes', create: 'Confirm shipment', edit: 'Edit scheduled shipment', delete: 'Delete scheduled shipment', deleteHelp: 'This removes a scheduled sample with no readings. Started and delivered shipments are preserved.', confirmDelete: 'Delete this scheduled shipment?', required: 'Required fields', details: 'Cargo & route', assignment: 'Resources & client', limits: 'Thermal ranges', review: 'Review & confirm',
    origin: 'Origin', destination: 'Destination', departure: 'Departure (local time)', arrival: 'Estimated arrival (local time)', minTemp: 'Minimum temperature (°C)', maxTemp: 'Maximum temperature (°C)', minHumidity: 'Minimum humidity (%)', maxHumidity: 'Maximum humidity (%)', selectVehicle: 'Select a vehicle', selectDriver: 'Select a driver', selectClient: 'Select a cargo client', resourceHelp: 'Assignments are validated for overlapping dates and vehicle capacity when you confirm.', rangeHelp: 'Sample ranges must suit your cargo. The coordinator remains responsible for validating safe settings.',
    shipmentCreated: 'Sample shipment scheduled.', shipmentUpdated: 'Sample shipment updated.', saved: 'Changes saved in this browser.', deleted: 'Scheduled sample deleted.', updated: 'Shipment updated.', start: 'Start trip', deliver: 'Mark delivered', cancelTrip: 'Cancel trip', actionNote: 'Action / cancellation note', transitionHelp: 'Trip status changes are recorded in the local history.', noReadings: 'No sample readings yet.', readings: 'Sample sensor readings', readingNotice: 'Stored sample values; this chart is not live telemetry.', addReading: 'Add sample reading', readingAdded: 'Sample reading saved.', latitude: 'Latitude', longitude: 'Longitude', timestamp: 'Timestamp', tableData: 'Reading values',
    correctiveAction: 'Record corrective action', resolve: 'Resolve alert', resolved: 'Resolved', openAlerts: 'Open', allAlerts: 'All alerts', temperatureAlert: 'Temperature deviation', humidityAlert: 'Humidity deviation', offlineAlert: 'Sensor signal missing', alertResolved: 'Corrective action recorded.', actions: 'Corrective actions', noActions: 'No corrective actions recorded.',
    notifications: 'Notifications', markRead: 'Mark all as read', noNotifications: 'No notifications.', noticeAlert: 'An alert needs review.', noticeCreated: 'A shipment was scheduled.', noticeTransit: 'A trip was started.', noticeDelivered: 'A shipment was delivered.', noticeCancelled: 'A trip was cancelled.',
    vehicles: 'Vehicles', drivers: 'Drivers', addVehicle: 'Add vehicle', addDriver: 'Add driver', enabled: 'Available for assignments', disabled: 'Inactive', enabledLabel: 'Allow new assignments', editResource: 'Edit resource', resourceLocked: 'Resources assigned to scheduled or active trips cannot be edited. Complete or cancel those trips first.',
    export: 'Download sample CSV', exportHelp: 'Includes readings and action history. Labelled as sample data, not an audit certificate.', timeline: 'Action history', noHistory: 'No actions recorded.', created: 'Scheduled', 'in-transit': 'In transit', sampleReading: 'Sample reading added', correctiveActionEvent: 'Corrective action recorded',
    name: 'Full name', email: 'Email', organization: 'Organization', profileHelp: 'Local profile only. Identity, passwords and account recovery require the future API.', role: 'Workspace role', localIdentity: 'Sample access · no authentication', chooseRole: 'Choose your perspective', chooseProfile: 'Sample profile', loginTitle: 'Keep every journey in range.', loginDescription: 'A focused workspace for refrigerated transport, from departure to delivery.', loginNotice: 'This TB1 version uses local sample data. Enter a role to explore it; no password or real account is requested.', createHelp: 'Create a profile in this browser only. Cargo clients see only shipments assigned to their profile.', useSample: 'Use an existing sample', recovery: 'Account recovery', recoveryHelp: 'No password is stored in this local version. Secure sign-in and recovery await the identity API.', consent: 'I understand this is a local sample profile and have read the terms.', requiredConsent: 'Accept the local sample notice to continue.', newClientEmpty: 'This new client has no assigned shipments. A coordinator can assign a shipment to this profile.', landing: 'Visit landing page', menu: 'Open navigation', close: 'Close', reset: 'Reset sample workspace', resetHelp: 'Resetting removes local changes and local profiles and restores the original sample.', resetConfirm: 'Reset local sample data?', preferences: 'Preferences', language: 'Language', sampleMode: 'Local sample mode', limitTitle: 'Next step: connect the service', limitText: 'Identity, connected sensors, shared persistence and server reports are pending API integration. This version demonstrates the frontend workflows.',
    errorTitle: 'Please review this', notFoundTitle: 'Shipment unavailable', notFoundText: 'This shipment does not exist or is not assigned to this profile.', emptyTitle: 'No shipments yet', emptyText: 'Scheduled shipments will appear here.', step: 'Step', of: 'of', selected: 'Selected', viewDetail: 'View shipment', readMore: 'View details',
    requiredFields: 'Complete all required cargo, route or resource fields.', sameRoute: 'Origin and destination must be different.', invalidWeight: 'Enter a positive weight or capacity.', invalidRange: 'Temperature minimum must be below maximum, between −50 and 50 °C.', invalidHumidity: 'Humidity minimum must be below maximum, between 0 and 100%.', invalidDates: 'Arrival must be later than departure.', missingAssignment: 'Select an available vehicle and driver.', missingCustomer: 'Select an existing cargo-client profile.', overCapacity: 'The cargo exceeds the selected vehicle capacity.', vehicleBusy: 'This vehicle already has a shipment overlapping these dates.', driverBusy: 'This driver already has a shipment overlapping these dates.', forbidden: 'This action is available only to an authorized workspace role.', notFound: 'This item is unavailable for this profile.', staleShipment: 'This shipment changed in another tab. Reload its details before editing.', editScheduledOnly: 'Only scheduled shipments can be edited.', deleteScheduledOnly: 'Only scheduled shipments without readings can be deleted.', invalidTransition: 'This trip status change is not permitted.', requiredAction: 'Enter a clear action note (at least 8 characters for a corrective action or incident).', readingsTransitOnly: 'Sample readings can be added only while the trip is in transit.', invalidReading: 'Enter valid temperature, humidity and coordinates.', alreadyResolved: 'This alert was already resolved.', invalidVehicle: 'Use a plate such as A1B-728 and a sensor reference.', duplicateVehicle: 'That plate or sensor is already assigned to another vehicle.', duplicateDriver: 'That licence reference already exists.', assignedResource: 'This resource is assigned to an active or scheduled shipment.', invalidProfile: 'Enter a name, organization and valid email.', duplicateProfile: 'A local profile already uses this email.', storageUnavailable: 'Browser storage is unavailable. Changes could not be saved.', unknownCommand: 'This action is not supported.', unexpected: 'The action could not be completed. Please try again.',
  },
  es: {
    zoomIn: 'Acercar', zoomOut: 'Alejar', mapContributors: 'colaboradores', seededShipment: 'Envío inicial de ejemplo', localShipment: 'Envío local de ejemplo', sampleWorkspace: 'Panel de ejemplo',
    acknowledged: 'Reconocida', notifyClient: 'Notificar al cliente asignado en este panel de ejemplo', recordAction: 'Guardar acción correctiva', correctiveSaved: 'Acción correctiva registrada. La alerta sigue abierta hasta añadir una lectura normal de ejemplo.', actionHelp: 'Describe qué se hizo y por qué (mínimo 8 caracteres). La acción reconoce la alerta. Sigue abierta hasta que una nueva lectura de ejemplo esté dentro de ambos rangos configurados.', futureDeparture: 'La salida de un envío nuevo debe ser futura.', noticeAction: 'Se registró una acción correctiva en tu envío.',
    incident: 'Incidencia registrada', recordIncident: 'Registrar incidencia', incidentHelp: 'Describe la incidencia y su contexto (mínimo 8 caracteres). Se guardará en el historial de este envío de ejemplo.',
    app: 'Panel de envíos', dashboard: 'Resumen', shipments: 'Envíos', alerts: 'Alertas', fleet: 'Flota y conductores', history: 'Historial y reportes', profile: 'Mi perfil', terms: 'Términos y datos', logout: 'Salir del panel', login: 'Entrar al panel de ejemplo', register: 'Crear perfil local',
    coordinator: 'Coordinador logístico', 'cargo-client': 'Cliente de carga', sample: 'Panel local de ejemplo', sampleShort: 'DATOS DE EJEMPLO', sampleNotice: 'Envíos y lecturas de ejemplo. Los cambios se guardan únicamente en este navegador.', sampleDate: 'Lecturas iniciales: 6 oct. 2026. Sin sensores conectados.', persistence: 'No se pudo leer el almacenamiento. Usa un navegador que permita guardar datos locales.',
    greeting: 'Tu cadena de frío, a la vista.', dashboardSubtitle: 'Sigue cada envío. Actúa sobre las excepciones.', clientGreeting: 'Conoce cómo viaja tu carga.', clientSubtitle: 'Temperatura, ruta y trazabilidad de tus envíos asignados.',
    newShipment: 'Programar envío', totalShipments: 'Total de envíos', inTransit: 'En tránsito', exceptions: 'Alertas abiertas', delivered: 'Entregado', scheduled: 'Programado', cancelled: 'Cancelado', all: 'Todos', normal: 'Dentro del rango', critical: 'Fuera del rango', offline: 'Sin señal', pending: 'Sin lectura',
    activeRoutes: 'Corredor de la costa', routeHelp: 'Posiciones ilustrativas de las lecturas de ejemplo guardadas.', loadMap: 'Cargar OpenStreetMap', mapPrivacy: 'El mapa se conecta a OpenStreetMap para cargar imágenes. Las posiciones son de ejemplo.', mapOffline: 'Si no cargan las imágenes, la ruta y las coordenadas siguen disponibles debajo.',
    attention: 'Requiere atención', noAlerts: 'No hay alertas abiertas en tu panel.', openAlert: 'Revisar alerta', viewAll: 'Ver todos', recentShipments: 'Seguimiento de envíos', shipment: 'Envío', cargo: 'Carga', route: 'Ruta', thermal: 'Estado térmico', temperature: 'Temperatura', humidity: 'Humedad', lastReading: 'Último ejemplo', lifecycle: 'Estado del viaje', customer: 'Cliente de carga', vehicle: 'Unidad', driver: 'Conductor', weight: 'Peso (t)', sensor: 'ID del sensor', capacity: 'Capacidad (t)', plate: 'Placa', license: 'Referencia de licencia',
    search: 'Buscar código, carga o ruta', filterStatus: 'Filtrar estado del viaje', filterThermal: 'Filtrar estado térmico', results: 'envíos', noResults: 'Ningún envío coincide con los filtros.', clearFilters: 'Limpiar filtros', open: 'Abrir', back: 'Atrás', next: 'Continuar', cancel: 'Cancelar', save: 'Guardar cambios', create: 'Confirmar envío', edit: 'Editar envío programado', delete: 'Eliminar envío programado', deleteHelp: 'Elimina un ejemplo programado sin lecturas. Se conservan los viajes iniciados y entregados.', confirmDelete: '¿Eliminar este envío programado?', required: 'Campos obligatorios', details: 'Carga y ruta', assignment: 'Recursos y cliente', limits: 'Rangos térmicos', review: 'Revisar y confirmar',
    origin: 'Origen', destination: 'Destino', departure: 'Salida (hora local)', arrival: 'Llegada estimada (hora local)', minTemp: 'Temperatura mínima (°C)', maxTemp: 'Temperatura máxima (°C)', minHumidity: 'Humedad mínima (%)', maxHumidity: 'Humedad máxima (%)', selectVehicle: 'Seleccionar unidad', selectDriver: 'Seleccionar conductor', selectClient: 'Seleccionar cliente', resourceHelp: 'Al confirmar se validan las fechas simultáneas y la capacidad de la unidad.', rangeHelp: 'Los rangos de ejemplo deben corresponder a tu carga. El coordinador debe validar los límites seguros.',
    shipmentCreated: 'Envío de ejemplo programado.', shipmentUpdated: 'Envío de ejemplo actualizado.', saved: 'Cambios guardados en este navegador.', deleted: 'Ejemplo programado eliminado.', updated: 'Envío actualizado.', start: 'Iniciar viaje', deliver: 'Marcar como entregado', cancelTrip: 'Cancelar viaje', actionNote: 'Nota de acción o cancelación', transitionHelp: 'Los cambios de estado quedan en el historial local.', noReadings: 'Aún no hay lecturas de ejemplo.', readings: 'Lecturas de ejemplo del sensor', readingNotice: 'Valores de ejemplo guardados; el gráfico no es telemetría en vivo.', addReading: 'Añadir lectura de ejemplo', readingAdded: 'Lectura de ejemplo guardada.', latitude: 'Latitud', longitude: 'Longitud', timestamp: 'Fecha y hora', tableData: 'Valores de las lecturas',
    correctiveAction: 'Registrar acción correctiva', resolve: 'Resolver alerta', resolved: 'Resuelta', openAlerts: 'Abiertas', allAlerts: 'Todas las alertas', temperatureAlert: 'Desviación de temperatura', humidityAlert: 'Desviación de humedad', offlineAlert: 'Sensor sin señal', alertResolved: 'Acción correctiva registrada.', actions: 'Acciones correctivas', noActions: 'Sin acciones correctivas registradas.',
    notifications: 'Notificaciones', markRead: 'Marcar todas como leídas', noNotifications: 'Sin notificaciones.', noticeAlert: 'Una alerta requiere revisión.', noticeCreated: 'Se programó un envío.', noticeTransit: 'Se inició un viaje.', noticeDelivered: 'Se entregó un envío.', noticeCancelled: 'Se canceló un viaje.',
    vehicles: 'Unidades', drivers: 'Conductores', addVehicle: 'Añadir unidad', addDriver: 'Añadir conductor', enabled: 'Disponible para asignaciones', disabled: 'Inactivo', enabledLabel: 'Permitir nuevas asignaciones', editResource: 'Editar recurso', resourceLocked: 'Los recursos asignados a viajes programados o activos no se pueden editar. Primero completa o cancela esos viajes.',
    export: 'Descargar CSV de ejemplo', exportHelp: 'Incluye lecturas e historial de acciones. Identificado como ejemplo, no como certificado de auditoría.', timeline: 'Historial de acciones', noHistory: 'Sin acciones registradas.', created: 'Programado', 'in-transit': 'En tránsito', sampleReading: 'Lectura de ejemplo añadida', correctiveActionEvent: 'Acción correctiva registrada',
    name: 'Nombre completo', email: 'Correo electrónico', organization: 'Organización', profileHelp: 'Perfil local. La identidad, contraseñas y recuperación de cuenta requieren la futura API.', role: 'Rol del panel', localIdentity: 'Acceso de ejemplo · sin autenticación', chooseRole: 'Elige tu perspectiva', chooseProfile: 'Perfil de ejemplo', loginTitle: 'Cada viaje, dentro del rango.', loginDescription: 'Un panel para el transporte refrigerado, desde la salida hasta la entrega.', loginNotice: 'Esta versión TB1 usa datos locales de ejemplo. Elige un rol para explorarla; no solicita contraseña ni una cuenta real.', createHelp: 'Crea un perfil solo en este navegador. Los clientes ven únicamente los envíos asignados a su perfil.', useSample: 'Usar un ejemplo existente', recovery: 'Recuperación de cuenta', recoveryHelp: 'Esta versión local no guarda contraseñas. El acceso seguro y la recuperación requieren la API de identidad.', consent: 'Entiendo que este perfil es local y de ejemplo y he leído los términos.', requiredConsent: 'Acepta el aviso del perfil local para continuar.', newClientEmpty: 'Este cliente nuevo no tiene envíos asignados. Un coordinador puede asignar un envío a este perfil.', landing: 'Visitar la landing page', menu: 'Abrir navegación', close: 'Cerrar', reset: 'Restablecer datos de ejemplo', resetHelp: 'Se eliminan cambios y perfiles locales y se recuperan los ejemplos originales.', resetConfirm: '¿Restablecer los datos locales?', preferences: 'Preferencias', language: 'Idioma', sampleMode: 'Modo local de ejemplo', limitTitle: 'Siguiente paso: conectar el servicio', limitText: 'La identidad, los sensores conectados, la persistencia compartida y los reportes del servidor requieren integración con la API. Esta versión demuestra los flujos del frontend.',
    errorTitle: 'Revisa estos datos', notFoundTitle: 'Envío no disponible', notFoundText: 'El envío no existe o no está asignado a este perfil.', emptyTitle: 'Aún no hay envíos', emptyText: 'Aquí aparecerán los envíos programados.', step: 'Paso', of: 'de', selected: 'Seleccionado', viewDetail: 'Ver envío', readMore: 'Ver detalles',
    requiredFields: 'Completa los campos obligatorios de carga, ruta o recursos.', sameRoute: 'El origen y destino deben ser diferentes.', invalidWeight: 'Ingresa un peso o capacidad mayor que cero.', invalidRange: 'La temperatura mínima debe ser menor que la máxima, entre −50 y 50 °C.', invalidHumidity: 'La humedad mínima debe ser menor que la máxima, entre 0 y 100%.', invalidDates: 'La llegada debe ser posterior a la salida.', missingAssignment: 'Selecciona una unidad y conductor disponibles.', missingCustomer: 'Selecciona un perfil de cliente existente.', overCapacity: 'La carga excede la capacidad de la unidad.', vehicleBusy: 'La unidad tiene otro envío con fechas simultáneas.', driverBusy: 'El conductor tiene otro envío con fechas simultáneas.', forbidden: 'Esta acción requiere un rol autorizado del panel.', notFound: 'Este elemento no está disponible para el perfil.', staleShipment: 'El envío cambió en otra pestaña. Recarga sus datos antes de editar.', editScheduledOnly: 'Solo se pueden editar envíos programados.', deleteScheduledOnly: 'Solo se pueden eliminar envíos programados sin lecturas.', invalidTransition: 'No se permite este cambio de estado.', requiredAction: 'Ingresa una nota clara (mínimo 8 caracteres al registrar una acción correctiva o incidencia).', readingsTransitOnly: 'Solo se añaden lecturas de ejemplo a viajes en tránsito.', invalidReading: 'Ingresa temperatura, humedad y coordenadas válidas.', alreadyResolved: 'Esta alerta ya fue resuelta.', invalidVehicle: 'Usa una placa como A1B-728 y una referencia de sensor.', duplicateVehicle: 'La placa o sensor ya está asignado a otra unidad.', duplicateDriver: 'La referencia de licencia ya existe.', assignedResource: 'El recurso está asignado a un envío activo o programado.', invalidProfile: 'Ingresa nombre, organización y correo válido.', duplicateProfile: 'Ya existe un perfil local con ese correo.', storageUnavailable: 'No está disponible el almacenamiento. No se guardaron los cambios.', unknownCommand: 'No se admite esta acción.', unexpected: 'No se pudo completar la acción. Inténtalo de nuevo.',
  },
};
let preferred = 'en';
try { if (localStorage.getItem('friotrack.language') === 'es') preferred = 'es'; } catch { /* English default */ }
export const language = ref(preferred);
export function t(key) { return dictionary[language.value][key] || dictionary.en[key] || key; }
export function setLanguage(value) {
  language.value = value === 'es' ? 'es' : 'en';
  document.documentElement.lang = language.value === 'es' ? 'es-419' : 'en-US';
  try { localStorage.setItem('friotrack.language', language.value); } catch { /* Keep working without preference persistence. */ }
}
export function formatDate(value) { return new Intl.DateTimeFormat(language.value === 'es' ? 'es-419' : 'en-US', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'America/Lima' }).format(new Date(value)); }
setLanguage(language.value);

