import { ref } from 'vue';
const dictionary = {
  en: {
    passwordMismatch: "The passwords do not match.",
    invalidPassword: "Use a password between 12 and 128 characters.",
    tooManyAttempts: "Too many attempts. Wait one minute and try again.",
    serviceUnavailable: "The service is unavailable. Please try again in a moment.",
    sessionExpired: "Your session has expired. Please sign in again.",
    invalidCredentials: "The email or password is incorrect.",
    accessHistory: "Keep a record of each journey",
    accessConditions: "Follow temperature and humidity",
    accessShipments: "Manage your shipments and routes",
    accessPermissions: "Your account determines the shipments and actions you can access.",
    newAccount: "Create a cargo client account",
    alreadyAccount: "Already have an account? Sign in",
    hidePassword: "Hide password",
    showPassword: "Show password",
    passwordHelp: "Use at least 12 characters.",
    confirmPassword: "Confirm password",
    password: "Password",
    zoomIn: 'Zoom in', zoomOut: 'Zoom out', mapContributors: 'contributors', seededShipment: "Shipment scheduled", localShipment: "Shipment scheduled", sampleWorkspace: "Operations",
    acknowledged: 'Acknowledged', notifyClient: 'Notify the assigned cargo client in this workspace', recordAction: 'Save corrective action', correctiveSaved: 'Corrective action recorded. The alert remains open until a normal reading is added.', actionHelp: 'Describe what was done and why (at least 8 characters). The action acknowledges the alert. It remains open until a new reading is within both configured ranges.', futureDeparture: 'A new shipment must depart in the future.', noticeAction: 'A corrective action was recorded for your shipment.',
    incident: 'Incident recorded', recordIncident: 'Record incident', incidentHelp: 'Describe the incident and context (at least 8 characters). It will be recorded in this shipment history.',
    app: 'Shipment workspace', dashboard: 'Overview', shipments: 'Shipments', alerts: 'Alerts', fleet: 'Fleet & drivers', history: 'History & reports', profile: 'My profile', terms: 'Terms & data', logout: "Sign out", login: "Sign in", register: "Create account",
    coordinator: 'Logistics coordinator', 'cargo-client': 'Cargo client', sample: "Workspace", sampleShort: "SIMULATED READINGS", sampleNotice: "Readings are simulated; no physical sensors are connected.", sampleDate: "Simulated readings · Oct 6, 2026", persistence: "This browser cannot keep your session. Allow session storage to remain signed in.",
    greeting: 'Your cold chain, in focus.', dashboardSubtitle: 'Follow each shipment. Act on the exceptions.', clientGreeting: 'Know how your cargo is travelling.', clientSubtitle: 'Temperature, route and traceability for your assigned shipments.',
    newShipment: 'Schedule shipment', totalShipments: 'Total shipments', inTransit: 'In transit', exceptions: 'Open alerts', delivered: 'Delivered', scheduled: 'Scheduled', cancelled: 'Cancelled', all: 'All', normal: 'Within range', critical: 'Out of range', offline: 'No signal', pending: 'Awaiting reading',
    activeRoutes: 'Coastal corridor', routeHelp: "Locations from the stored simulated readings.", loadMap: 'Load OpenStreetMap', mapPrivacy: "Loading the map connects to OpenStreetMap for tiles. Positions come from simulated readings.", mapOffline: 'If tiles cannot load, the route and coordinates remain available below.',
    attention: 'Needs attention', noAlerts: 'No open alerts in your workspace.', openAlert: 'Review alert', viewAll: 'View all', recentShipments: 'Shipment watchlist', shipment: 'Shipment', cargo: 'Cargo', route: 'Route', thermal: 'Thermal status', temperature: 'Temperature', humidity: 'Humidity', lastReading: "Latest reading", lifecycle: 'Trip status', customer: 'Cargo client', vehicle: 'Vehicle', driver: 'Driver', weight: 'Weight (t)', sensor: 'Sensor ID', capacity: 'Capacity (t)', plate: 'Plate', license: 'Licence reference',
    search: 'Search ID, cargo or route', filterStatus: 'Filter trip status', filterThermal: 'Filter thermal status', results: 'shipments', noResults: 'No shipments match these filters.', clearFilters: 'Clear filters', open: 'Open', back: 'Back', next: 'Continue', cancel: 'Cancel', save: 'Save changes', create: 'Confirm shipment', edit: 'Edit scheduled shipment', delete: 'Delete scheduled shipment', deleteHelp: "Removes a scheduled shipment without readings. Started and delivered shipments are preserved.", confirmDelete: 'Delete this scheduled shipment?', required: 'Required fields', details: 'Cargo & route', assignment: 'Resources & client', limits: 'Thermal ranges', review: 'Review & confirm',
    origin: 'Origin', destination: 'Destination', departure: 'Departure (local time)', arrival: 'Estimated arrival (local time)', minTemp: 'Minimum temperature (°C)', maxTemp: 'Maximum temperature (°C)', minHumidity: 'Minimum humidity (%)', maxHumidity: 'Maximum humidity (%)', selectVehicle: 'Select a vehicle', selectDriver: 'Select a driver', selectClient: 'Select a cargo client', resourceHelp: 'Assignments are validated for overlapping dates and vehicle capacity when you confirm.', rangeHelp: 'Configured ranges must suit your cargo. The coordinator remains responsible for validating safe settings.',
    shipmentCreated: "Shipment scheduled.", shipmentUpdated: "Shipment updated.", saved: "Changes saved.", deleted: "Scheduled shipment deleted.", updated: 'Shipment updated.', start: 'Start trip', deliver: 'Mark delivered', cancelTrip: 'Cancel trip', actionNote: 'Action / cancellation note', transitionHelp: "Trip status changes are recorded in the shipment history.", noReadings: "No readings recorded yet.", readings: "Temperature and humidity", readingNotice: "Simulated readings; no physical sensors are connected.", addReading: "Add simulated reading", readingAdded: "Reading saved.", latitude: 'Latitude', longitude: 'Longitude', timestamp: 'Timestamp', tableData: 'Reading values',
    correctiveAction: 'Record corrective action', resolve: 'Resolve alert', resolved: 'Resolved', openAlerts: 'Open', allAlerts: 'All alerts', temperatureAlert: 'Temperature deviation', humidityAlert: 'Humidity deviation', offlineAlert: 'Sensor signal missing', alertResolved: 'Corrective action recorded.', actions: 'Corrective actions', noActions: 'No corrective actions recorded.',
    notifications: 'Notifications', markRead: 'Mark all as read', noNotifications: 'No notifications.', noticeAlert: 'An alert needs review.', noticeCreated: 'A shipment was scheduled.', noticeTransit: 'A trip was started.', noticeDelivered: 'A shipment was delivered.', noticeCancelled: 'A trip was cancelled.',
    vehicles: 'Vehicles', drivers: 'Drivers', addVehicle: 'Add vehicle', addDriver: 'Add driver', enabled: 'Available for assignments', disabled: 'Inactive', enabledLabel: 'Allow new assignments', editResource: 'Edit resource', resourceLocked: 'Resources assigned to scheduled or active trips cannot be edited. Complete or cancel those trips first.',
    export: "Download CSV", exportHelp: "Includes readings and action history. Simulated readings are identified in the report.", timeline: 'Action history', noHistory: 'No actions recorded.', created: 'Scheduled', 'in-transit': 'In transit', sampleReading: "Simulated reading added", correctiveActionEvent: 'Corrective action recorded',
    name: 'Full name', email: 'Email', organization: 'Organization', profileHelp: "Keep your contact details and organization up to date.", role: 'Workspace role', localIdentity: "Your account", loginTitle: 'Keep every journey in range.', loginDescription: 'A focused workspace for refrigerated transport, from departure to delivery.', loginNotice: "Enter your email and password to access your workspace.", createHelp: "Create a cargo client account to follow shipments assigned to your organization.", useSample: "Sign in", consent: "I accept the", requiredConsent: "Accept the terms to continue.", newClientEmpty: 'This new client has no assigned shipments. A coordinator can assign a shipment to this profile.', landing: 'Visit landing page', menu: 'Open navigation', close: 'Close', preferences: 'Preferences', language: 'Language', sampleMode: "Workspace", errorTitle: 'Please review this', notFoundTitle: 'Shipment unavailable', notFoundText: 'This shipment does not exist or is not assigned to this profile.', emptyTitle: 'No shipments yet', emptyText: 'Scheduled shipments will appear here.', step: 'Step', of: 'of', selected: 'Selected', viewDetail: 'View shipment', readMore: 'View details',
    requiredFields: 'Complete all required cargo, route or resource fields.', sameRoute: 'Origin and destination must be different.', invalidWeight: 'Enter a positive weight or capacity.', invalidRange: 'Temperature minimum must be below maximum, between −50 and 50 °C.', invalidHumidity: 'Humidity minimum must be below maximum, between 0 and 100%.', invalidDates: 'Arrival must be later than departure.', missingAssignment: 'Select an available vehicle and driver.', missingCustomer: 'Select an existing cargo-client profile.', overCapacity: 'The cargo exceeds the selected vehicle capacity.', vehicleBusy: 'This vehicle already has a shipment overlapping these dates.', driverBusy: 'This driver already has a shipment overlapping these dates.', forbidden: 'This action is available only to an authorized workspace role.', notFound: 'This item is unavailable for this profile.', staleShipment: 'This shipment changed in another tab. Reload its details before editing.', editScheduledOnly: 'Only scheduled shipments can be edited.', deleteScheduledOnly: 'Only scheduled shipments without readings can be deleted.', invalidTransition: 'This trip status change is not permitted.', requiredAction: 'Enter a clear action note (at least 8 characters for a corrective action or incident).', readingsTransitOnly: 'Sample readings can be added only while the trip is in transit.', invalidReading: 'Enter valid temperature, humidity and coordinates.', alreadyResolved: 'This alert was already resolved.', invalidVehicle: 'Use a plate such as A1B-728 and a sensor reference.', duplicateVehicle: 'That plate or sensor is already assigned to another vehicle.', duplicateDriver: 'That licence reference already exists.', assignedResource: 'This resource is assigned to an active or scheduled shipment.', invalidProfile: 'Enter a name, organization and valid email.', duplicateProfile: "An account with this email already exists.", storageUnavailable: 'Browser storage is unavailable. Changes could not be saved.', unknownCommand: 'This action is not supported.', unexpected: 'The action could not be completed. Please try again.',
  },
  es: {
    passwordMismatch: "Las contraseñas no coinciden.",
    invalidPassword: "Usa una contraseña de entre 12 y 128 caracteres.",
    tooManyAttempts: "Demasiados intentos. Espera un minuto y vuelve a intentarlo.",
    serviceUnavailable: "El servicio no está disponible. Inténtalo de nuevo en un momento.",
    sessionExpired: "Tu sesión venció. Inicia sesión nuevamente.",
    invalidCredentials: "El correo o la contraseña son incorrectos.",
    accessHistory: "Conserva el historial de cada viaje",
    accessConditions: "Consulta temperatura y humedad",
    accessShipments: "Gestiona tus envíos y rutas",
    accessPermissions: "Tu cuenta determina qué envíos y acciones puedes consultar.",
    newAccount: "Crear una cuenta de cliente de carga",
    alreadyAccount: "¿Ya tienes una cuenta? Inicia sesión",
    hidePassword: "Ocultar contraseña",
    showPassword: "Mostrar contraseña",
    passwordHelp: "Usa al menos 12 caracteres.",
    confirmPassword: "Confirmar contraseña",
    password: "Contraseña",
    zoomIn: 'Acercar', zoomOut: 'Alejar', mapContributors: 'colaboradores', seededShipment: "Envío programado", localShipment: "Envío programado", sampleWorkspace: "Operaciones",
    acknowledged: 'Reconocida', notifyClient: 'Notificar al cliente asignado en este panel', recordAction: 'Guardar acción correctiva', correctiveSaved: 'Acción correctiva registrada. La alerta sigue abierta hasta añadir una lectura normal.', actionHelp: 'Describe qué se hizo y por qué (mínimo 8 caracteres). La acción reconoce la alerta. Sigue abierta hasta que una nueva lectura simulada esté dentro de ambos rangos configurados.', futureDeparture: 'La salida de un envío nuevo debe ser futura.', noticeAction: 'Se registró una acción correctiva en tu envío.',
    incident: 'Incidencia registrada', recordIncident: 'Registrar incidencia', incidentHelp: 'Describe la incidencia y su contexto (mínimo 8 caracteres). Se guardará en el historial de este envío.',
    app: 'Panel de envíos', dashboard: 'Resumen', shipments: 'Envíos', alerts: 'Alertas', fleet: 'Flota y conductores', history: 'Historial y reportes', profile: 'Mi perfil', terms: 'Términos y datos', logout: "Cerrar sesión", login: "Iniciar sesión", register: "Crear cuenta",
    coordinator: 'Coordinador logístico', 'cargo-client': 'Cliente de carga', sample: "Espacio de trabajo", sampleShort: "LECTURAS SIMULADAS", sampleNotice: "Las lecturas son simuladas; no hay sensores físicos conectados.", sampleDate: "Lecturas simuladas · 6 de octubre de 2026", persistence: "Este navegador no puede conservar tu sesión. Permite el almacenamiento de sesión para mantener el acceso.",
    greeting: 'Tu cadena de frío, a la vista.', dashboardSubtitle: 'Sigue cada envío. Actúa sobre las excepciones.', clientGreeting: 'Conoce cómo viaja tu carga.', clientSubtitle: 'Temperatura, ruta y trazabilidad de tus envíos asignados.',
    newShipment: 'Programar envío', totalShipments: 'Total de envíos', inTransit: 'En tránsito', exceptions: 'Alertas abiertas', delivered: 'Entregado', scheduled: 'Programado', cancelled: 'Cancelado', all: 'Todos', normal: 'Dentro del rango', critical: 'Fuera del rango', offline: 'Sin señal', pending: 'Sin lectura',
    activeRoutes: 'Corredor de la costa', routeHelp: "Ubicaciones de las lecturas simuladas guardadas.", loadMap: 'Cargar OpenStreetMap', mapPrivacy: "El mapa se conecta a OpenStreetMap para cargar imágenes. Las posiciones provienen de lecturas simuladas.", mapOffline: 'Si no cargan las imágenes, la ruta y las coordenadas siguen disponibles debajo.',
    attention: 'Requiere atención', noAlerts: 'No hay alertas abiertas en tu panel.', openAlert: 'Revisar alerta', viewAll: 'Ver todos', recentShipments: 'Seguimiento de envíos', shipment: 'Envío', cargo: 'Carga', route: 'Ruta', thermal: 'Estado térmico', temperature: 'Temperatura', humidity: 'Humedad', lastReading: "Última lectura", lifecycle: 'Estado del viaje', customer: 'Cliente de carga', vehicle: 'Unidad', driver: 'Conductor', weight: 'Peso (t)', sensor: 'ID del sensor', capacity: 'Capacidad (t)', plate: 'Placa', license: 'Referencia de licencia',
    search: 'Buscar código, carga o ruta', filterStatus: 'Filtrar estado del viaje', filterThermal: 'Filtrar estado térmico', results: 'envíos', noResults: 'Ningún envío coincide con los filtros.', clearFilters: 'Limpiar filtros', open: 'Abrir', back: 'Atrás', next: 'Continuar', cancel: 'Cancelar', save: 'Guardar cambios', create: 'Confirmar envío', edit: 'Editar envío programado', delete: 'Eliminar envío programado', deleteHelp: "Elimina un envío programado sin lecturas. Se conservan los viajes iniciados y entregados.", confirmDelete: '¿Eliminar este envío programado?', required: 'Campos obligatorios', details: 'Carga y ruta', assignment: 'Recursos y cliente', limits: 'Rangos térmicos', review: 'Revisar y confirmar',
    origin: 'Origen', destination: 'Destino', departure: 'Salida (hora local)', arrival: 'Llegada estimada (hora local)', minTemp: 'Temperatura mínima (°C)', maxTemp: 'Temperatura máxima (°C)', minHumidity: 'Humedad mínima (%)', maxHumidity: 'Humedad máxima (%)', selectVehicle: 'Seleccionar unidad', selectDriver: 'Seleccionar conductor', selectClient: 'Seleccionar cliente', resourceHelp: 'Al confirmar se validan las fechas simultáneas y la capacidad de la unidad.', rangeHelp: "Los rangos configurados deben corresponder a tu carga. El coordinador debe validar los límites seguros.",
    shipmentCreated: "Envío programado.", shipmentUpdated: "Envío actualizado.", saved: "Cambios guardados.", deleted: "Envío programado eliminado.", updated: 'Envío actualizado.', start: 'Iniciar viaje', deliver: 'Marcar como entregado', cancelTrip: 'Cancelar viaje', actionNote: 'Nota de acción o cancelación', transitionHelp: "Los cambios de estado quedan registrados en el historial del envío.", noReadings: "Aún no hay lecturas registradas.", readings: "Temperatura y humedad", readingNotice: "Lecturas simuladas; no hay sensores físicos conectados.", addReading: "Añadir lectura simulada", readingAdded: "Lectura guardada.", latitude: 'Latitud', longitude: 'Longitud', timestamp: 'Fecha y hora', tableData: 'Valores de las lecturas',
    correctiveAction: 'Registrar acción correctiva', resolve: 'Resolver alerta', resolved: 'Resuelta', openAlerts: 'Abiertas', allAlerts: 'Todas las alertas', temperatureAlert: 'Desviación de temperatura', humidityAlert: 'Desviación de humedad', offlineAlert: 'Sensor sin señal', alertResolved: 'Acción correctiva registrada.', actions: 'Acciones correctivas', noActions: 'Sin acciones correctivas registradas.',
    notifications: 'Notificaciones', markRead: 'Marcar todas como leídas', noNotifications: 'Sin notificaciones.', noticeAlert: 'Una alerta requiere revisión.', noticeCreated: 'Se programó un envío.', noticeTransit: 'Se inició un viaje.', noticeDelivered: 'Se entregó un envío.', noticeCancelled: 'Se canceló un viaje.',
    vehicles: 'Unidades', drivers: 'Conductores', addVehicle: 'Añadir unidad', addDriver: 'Añadir conductor', enabled: 'Disponible para asignaciones', disabled: 'Inactivo', enabledLabel: 'Permitir nuevas asignaciones', editResource: 'Editar recurso', resourceLocked: 'Los recursos asignados a viajes programados o activos no se pueden editar. Primero completa o cancela esos viajes.',
    export: "Descargar CSV", exportHelp: "Incluye lecturas e historial de acciones. Las lecturas simuladas se identifican en el reporte.", timeline: 'Historial de acciones', noHistory: 'Sin acciones registradas.', created: 'Programado', 'in-transit': 'En tránsito', sampleReading: "Lectura simulada añadida", correctiveActionEvent: 'Acción correctiva registrada',
    name: 'Nombre completo', email: 'Correo electrónico', organization: 'Organización', profileHelp: "Mantén actualizados tus datos de contacto y organización.", role: 'Rol del panel', localIdentity: "Tu cuenta", loginTitle: 'Cada viaje, dentro del rango.', loginDescription: 'Un panel para el transporte refrigerado, desde la salida hasta la entrega.', loginNotice: "Ingresa tu correo y contraseña para acceder a tu espacio de trabajo.", createHelp: "Crea una cuenta de cliente de carga para consultar los envíos asignados a tu organización.", useSample: "Iniciar sesión", consent: "Acepto los", requiredConsent: "Acepta los términos para continuar.", newClientEmpty: 'Este cliente nuevo no tiene envíos asignados. Un coordinador puede asignar un envío a este perfil.', landing: 'Visitar la landing page', menu: 'Abrir navegación', close: 'Cerrar', preferences: 'Preferencias', language: 'Idioma', sampleMode: "Espacio de trabajo", errorTitle: 'Revisa estos datos', notFoundTitle: 'Envío no disponible', notFoundText: 'El envío no existe o no está asignado a este perfil.', emptyTitle: 'Aún no hay envíos', emptyText: 'Aquí aparecerán los envíos programados.', step: 'Paso', of: 'de', selected: 'Seleccionado', viewDetail: 'Ver envío', readMore: 'Ver detalles',
    requiredFields: 'Completa los campos obligatorios de carga, ruta o recursos.', sameRoute: 'El origen y destino deben ser diferentes.', invalidWeight: 'Ingresa un peso o capacidad mayor que cero.', invalidRange: 'La temperatura mínima debe ser menor que la máxima, entre −50 y 50 °C.', invalidHumidity: 'La humedad mínima debe ser menor que la máxima, entre 0 y 100%.', invalidDates: 'La llegada debe ser posterior a la salida.', missingAssignment: 'Selecciona una unidad y conductor disponibles.', missingCustomer: 'Selecciona un perfil de cliente existente.', overCapacity: 'La carga excede la capacidad de la unidad.', vehicleBusy: 'La unidad tiene otro envío con fechas simultáneas.', driverBusy: 'El conductor tiene otro envío con fechas simultáneas.', forbidden: 'Esta acción requiere un rol autorizado del panel.', notFound: 'Este elemento no está disponible para el perfil.', staleShipment: 'El envío cambió en otra pestaña. Recarga sus datos antes de editar.', editScheduledOnly: 'Solo se pueden editar envíos programados.', deleteScheduledOnly: 'Solo se pueden eliminar envíos programados sin lecturas.', invalidTransition: 'No se permite este cambio de estado.', requiredAction: 'Ingresa una nota clara (mínimo 8 caracteres al registrar una acción correctiva o incidencia).', readingsTransitOnly: 'Solo se añaden lecturas simuladas a viajes en tránsito.', invalidReading: 'Ingresa temperatura, humedad y coordenadas válidas.', alreadyResolved: 'Esta alerta ya fue resuelta.', invalidVehicle: 'Usa una placa como A1B-728 y una referencia de sensor.', duplicateVehicle: 'La placa o sensor ya está asignado a otra unidad.', duplicateDriver: 'La referencia de licencia ya existe.', assignedResource: 'El recurso está asignado a un envío activo o programado.', invalidProfile: 'Ingresa nombre, organización y correo válido.', duplicateProfile: "Ya existe una cuenta con ese correo.", storageUnavailable: 'No está disponible el almacenamiento. No se guardaron los cambios.', unknownCommand: 'No se admite esta acción.', unexpected: 'No se pudo completar la acción. Inténtalo de nuevo.',
  },
};
let preferred = 'en';
try { if (localStorage.getItem('friotrack.language') === 'es') preferred = 'es'; } catch { /* English default */ }
export const language = ref(preferred);
export function t(key) { return dictionary[language.value][key] || dictionary.en[key] || key; }
export function setLanguage(value) {
  language.value = value === 'es' ? 'es' : 'en';
  document.documentElement.lang = language.value === 'es' ? 'es-419' : 'en-US';
  try { localStorage.setItem('friotrack.language', language.value); } catch { /* Keep working without preference persistence. */ }
}
export function formatDate(value) { return new Intl.DateTimeFormat(language.value === 'es' ? 'es-419' : 'en-US', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'America/Lima' }).format(new Date(value)); }
setLanguage(language.value);

