<script setup>
import { computed, reactive, ref } from 'vue';
import { data, execute } from '../infrastructure/demo-repository.js';
import { t } from '../shared/i18n.js';
import { announce, errorText } from '../shared/feedback.js';
const tab = ref('vehicles'), editing = ref(''), dialogOpen = ref(false), error = ref('');
const draft = reactive({});
const resources = computed(() => data.value[tab.value]);
const assigned = (id) => data.value.shipments.some(item => ['scheduled', 'in-transit'].includes(item.status) && item[tab.value === 'vehicles' ? 'vehicleId' : 'driverId'] === id);
function open(item) { editing.value = item?.id || ''; Object.keys(draft).forEach(key => delete draft[key]); Object.assign(draft, item || (tab.value === 'vehicles' ? { plate: '', capacity: '', sensor: '', enabled: true } : { name: '', license: '', enabled: true })); error.value = ''; dialogOpen.value = true; }
function save() { try { execute(tab.value === 'vehicles' ? 'saveVehicle' : 'saveDriver', { ...draft, id: editing.value || undefined }); dialogOpen.value = false; announce('saved'); } catch (failure) { error.value = errorText(failure); } }
</script>
<template>
  <div class="page-heading"><div><div class="eyebrow">{{ t('sampleShort') }}</div><h1>{{ t('fleet') }}</h1><p>{{ t('resourceLocked') }}</p></div><PButton :label="t(tab === 'vehicles' ? 'addVehicle' : 'addDriver')" icon="pi pi-plus" @click="open()"/></div>
  <div class="section-tabs" role="group" :aria-label="t('fleet')"><button v-for="type in ['vehicles', 'drivers']" :key="type" :aria-pressed="tab === type" @click="tab = type"><i :class="`pi pi-${type === 'vehicles' ? 'truck' : 'id-card'}`" aria-hidden="true"></i>{{ t(type) }} <span>{{ data[type].length }}</span></button></div>
  <div class="resource-grid"><article v-for="item in resources" :key="item.id" class="panel resource-card"><div class="resource-head"><span class="resource-icon"><i :class="`pi pi-${tab === 'vehicles' ? 'truck' : 'user'}`" aria-hidden="true"></i></span><PButton icon="pi pi-pencil" :aria-label="`${t('editResource')} ${item.plate || item.name}`" text :disabled="assigned(item.id)" @click="open(item)"/></div><h2>{{ item.plate || item.name }}</h2><dl v-if="tab === 'vehicles'"><div><dt>{{ t('capacity') }}</dt><dd>{{ item.capacity }} t</dd></div><div><dt>{{ t('sensor') }}</dt><dd>{{ item.sensor }}</dd></div></dl><dl v-else><div><dt>{{ t('license') }}</dt><dd>{{ item.license }}</dd></div></dl><span :class="['status', item.enabled ? 'normal' : 'offline']"><i :class="`pi pi-${item.enabled ? 'check-circle' : 'ban'}`" aria-hidden="true"></i>{{ t(item.enabled ? 'enabled' : 'disabled') }}</span><p v-if="assigned(item.id)" class="resource-assigned"><i class="pi pi-lock" aria-hidden="true"></i>{{ t('selected') }}</p></article></div>
  <PDialog v-model:visible="dialogOpen" modal :header="t(editing ? 'editResource' : tab === 'vehicles' ? 'addVehicle' : 'addDriver')" :style="{ width: '32rem', maxWidth: '94vw' }"><form id="resource-form" @submit.prevent="save"><template v-if="tab === 'vehicles'"><div class="field"><label for="resource-plate">{{ t('plate') }} *</label><PInputText id="resource-plate" v-model="draft.plate" placeholder="A1B-728" required maxlength="7" pattern="[A-Za-z0-9]{3}-[A-Za-z0-9]{3}"/></div><div class="field"><label for="resource-capacity">{{ t('capacity') }} *</label><PInputText id="resource-capacity" v-model="draft.capacity" type="number" min="0.01" max="100" step="0.01" required/></div><div class="field"><label for="resource-sensor">{{ t('sensor') }} *</label><PInputText id="resource-sensor" v-model="draft.sensor" required maxlength="50"/></div></template><template v-else><div class="field"><label for="resource-name">{{ t('name') }} *</label><PInputText id="resource-name" v-model="draft.name" required maxlength="90"/></div><div class="field"><label for="resource-license">{{ t('license') }} *</label><PInputText id="resource-license" v-model="draft.license" required maxlength="50"/></div></template><div class="checkbox-field"><PCheckbox v-model="draft.enabled" :binary="true" inputId="resource-enabled"/><label for="resource-enabled">{{ t('enabledLabel') }}</label></div><PMessage v-if="error" severity="error" class="form-error">{{ error }}</PMessage></form><template #footer><PButton :label="t('cancel')" text @click="dialogOpen = false"/><PButton :label="t('save')" type="submit" form="resource-form" icon="pi pi-check"/></template></PDialog>
</template>
